/**
 * Generates the JSON Schema catalog for outbound webhook events, derived
 * directly from the Zod schemas in `src/webhookEvents.ts`. Run via
 * `npm run schemas:generate`.
 *
 * The Zod schemas are the single source of truth; this script exists so
 * non-TypeScript webhook consumers (or JSON Schema validators in any
 * language) can validate deliveries without depending on this package.
 *
 * Output: docs/schemas/webhooks/*.schema.json (relative to repo root),
 * plus a catalog.json index describing every event type.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import {
  WEBHOOK_SCHEMA_VERSION,
  WebhookEnvelopeSchema,
  WebhookEventPayloadSchemas,
} from "../src/webhookEvents";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "..", "..", "..", "docs", "schemas", "webhooks");

mkdirSync(OUT_DIR, { recursive: true });

function write(filename: string, schema: unknown): void {
  const path = join(OUT_DIR, filename);
  writeFileSync(path, JSON.stringify(schema, null, 2) + "\n", "utf8");
  console.log(`wrote ${path}`);
}

// Envelope schema
write("envelope.schema.json", z.toJSONSchema(WebhookEnvelopeSchema));

// One schema file per event type's payload
const catalogEntries: Array<{ eventType: string; payloadSchema: string }> = [];
for (const [eventType, schema] of Object.entries(WebhookEventPayloadSchemas)) {
  const filename = `${eventType}.payload.schema.json`;
  write(filename, z.toJSONSchema(schema));
  catalogEntries.push({ eventType, payloadSchema: `./${filename}` });
}

// Top-level catalog index
write("catalog.json", {
  $comment:
    "Generated by packages/api-schemas/scripts/generate-webhook-json-schema.ts — do not hand-edit.",
  schemaVersion: WEBHOOK_SCHEMA_VERSION,
  envelopeSchema: "./envelope.schema.json",
  events: catalogEntries,
});
